### ISSUE TITLE
Create ModelRepository for H2O

### ISSUE THREAD

**Issue by jkukowski** [prinz-nussknacker/prinz#131]

**Comment by kantoniak** [comment]
FYI H2O supports multiple input modes, see:
* https://github.com/prinz-nussknacker/prinz/commit/e12e963f78011352457a3d8beb12d619249ce542
* [hex.genmodel.MojoReaderBackendFactory](https://github.com/h2oai/h2o-3/blob/master/h2o-genmodel/src/main/java/hex/genmodel/MojoReaderBackendFactory.java)
