### ISSUE TITLE
Consider the caching strategy in H2O model

### ISSUE THREAD

**Issue by avan1235** [prinz-nussknacker/prinz#156]
MojoReaderBackend can be read and cached on disk or to memory. Actually we use memory by default (no configuration possible). Discuss and try to design the MojoReaderBackend with configurable cache storage

**Comment by Jadw1** [comment]
What do u mean by no configuration possible? Can't we add another variable to config?

**Comment by avan1235** [comment]
It's harcoded in [H2OModel](https://github.com/prinz-nussknacker/prinz/blob/dev/h2o/prinz_h2o/src/main/scala/pl/touk/nussknacker/prinz/h2o/model/H2OModel.scala) and I was cleaning the code so I decided to move this TODO from code to issue. For now there is no field for this kind of configuration in our config definition and imo we should ask supervisors if it should be configurable

**Comment by kantoniak** [comment]
Code for reference: https://github.com/prinz-nussknacker/prinz/commit/73bf7b08d7616c4c5093eb7813e31b4afec7d5de#diff-d91f36ed2a3d01dd9227d68f75b7470211113f5df979fe60c8c238ea0a861b56R10
