### ISSUE TITLE
Configure MLflow docker instance to give information about models run location

### ISSUE THREAD

**Issue by avan1235** [prinz-nussknacker/prinz#20]
Current configuration of MLflow environment servers single model as we can see in this [file](https://github.com/prinz-nussknacker/prinz/blob/master/dev-environment/mlflow/run.sh). But MLflow after starting serving this model (or even earlier when running the model) add model to registered models database so it can be listed using the endpoint specified [here](https://www.mlflow.org/docs/latest/rest-api.html#list-registeredmodels). When you read this documentation there is only specification of something named "run_link" [here](https://www.mlflow.org/docs/latest/rest-api.html#mlflowmodelversion). We should get to know and configure MLflow to serve the information about deployed model location (I think so but I'm not 100% sure) or at least try to figure out what information we should get from MLflow and from where (which endpoints) to give nussknacker the ability to send data to model and receive some results.

**Comment by jkukowski** [comment]
Deployed model location should be set up in Nussknacker configuration files.

**Comment by avan1235** [comment]
I just place here some reference how it is solved on databricks https://docs.microsoft.com/en-us/azure/databricks/applications/mlflow/model-serving#model-serving-from-model-registry. Maybe we should do something similiar but then we need to introduce some proxy to our environment to redirect calls to */invocations to specified model

**Comment by avan1235** [comment]
I close this issue as we already defined the convention of model serving url (will stick to databrisk similiar pattern)
